### ISSUE TITLE
end of test behavior

### ISSUE THREAD

**Issue by jstupak** [psi46/elComandante#20]
At FNAL, we use water at 10C as coolant.  When the tests end, elComandante relinquishes control of the cold box, and if no one pays attention the temperature inside the cold box eventually falls to 10C, and the humidity slowly rises.  This is dangerous during the summer, as the dew point right now is 13C.

Can we instead allow the cooling box client to maintain control of the coldbox, and remain in heating mode at the final heating temperature, until the user terminates the clients?

**Comment by veloxid** [comment]
Hi,
Since we are now also using cold water as coolant we already did the change but did not commited it yet. 
Should be in the master branch after commit 75bc1731e364253ed91b436c7842681609a4d365

Please try and check weather this suits for you.
Cheers
Felix

**Comment by jstupak** [comment]
Thanks Felix!  With this update I see it heats to 20 and stays there, but I get:

Traceback (most recent call last):
  File "./el_comandante.py", line 805, in <module>
    elComandante.run()
  File "./el_comandante.py", line 716, in run
    agente.final_test_cleanup()
  File "/home/fnalpix1/elComandante/elComandante/coolingBox_agente.py", line 133, in final_test_cleanup
    userQueries.query_any("Press ENTER after taking out the modules ", self.log)
NameError: global name 'userQueries' is not defined

**Comment by veloxid** [comment]
Didn't import userQueries, fixed - please check
